server:
  port: 8082

spring:
  application:
    name: TravelProject
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel_guide_platform?useSSL=false&serverTimezone=UTC&autoReconnect=true
    username: root
    password: 123321
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp


logging:
  level:
    com:
      travel:
        mapper: debug
        service: info
        controller: info
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.travel.entity
  configuration:
    map-underscore-to-camel-case: true

app:
  jwt:
    secret: 6a701ec8714c4e99af80e7329adf06475b26d01c4a0502c48a71d86e76b6d6e9
    access-expire-minutes: 120
  oss:
    endpoint: oss-cn-guangzhou.aliyuncs.com
    access-key-id: LTAI5tBzVgNNNNNfJq8XD9jy
    access-key-secret: KzoUlxO4YmDxDZne5nviJVjnr3ri9P
    bucket-name: travel-shared-platform
#    bucket-name: web-talis-0717
